{{- if .Values.cli.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feature.cli.fullname" . }}
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: cli
spec:
  replicas: {{ .Values.cli.replicaCount }}
  selector:
    matchLabels:
      {{- include "feature.cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "feature.cli.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cli
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.cli.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: ["/app/feature-cli"]
          envFrom:
            - configMapRef:
                name: {{ include "feature.cli.fullname" . }}
          {{- with .Values.cli.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
