{{- if and .Values.service.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "feature.fullname" . }}
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "feature.fullname" . }}
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "feature.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "feature.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
