{{- if and .Values.ui.enabled .Values.ui.auth.enabled (not .Values.ui.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feature.ui.fullname" . }}-auth
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
type: Opaque
data:
  username: {{ .Values.ui.auth.username | b64enc | quote }}
  password: {{ .Values.ui.auth.password | b64enc | quote }}
{{- end }}
