{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feature.ui.fullname" . }}
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "feature.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "feature.ui.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ui
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.ui.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "feature.ui.fullname" . }}
          {{- if .Values.ui.auth.enabled }}
          env:
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-auth" (include "feature.ui.fullname" .)) .Values.ui.auth.existingSecret }}
                  key: username
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-auth" (include "feature.ui.fullname" .)) .Values.ui.auth.existingSecret }}
                  key: password
          {{- end }}
          {{- if .Values.ui.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ print (.Values.ui.subpath | default "") "/health" }}
              port: http
          {{- end }}
          {{- if .Values.ui.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ print (.Values.ui.subpath | default "") "/health" }}
              port: http
          {{- end }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
