{{- if and .Values.ui.enabled .Values.ui.authentication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
type: Opaque
data:
  {{- $password := .Values.ui.authentication.password }}
  {{- if eq $password "" }}
  {{- $password = randAlphaNum 24 }}
  {{- end }}
  AUTHENTICATION_PASSWORD: {{ $password | b64enc | quote }}
{{- end }}
