{{- if and .Values.ui.enabled .Values.service.authentication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feature.ui.fullname" . }}
  labels:
    {{- include "feature.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
type: Opaque
data:
  {{- $password := .Values.service.authentication.password }}
  {{- if eq $password "" }}
  {{- $password = randAlphaNum 24 }}
  {{- end }}
  PASSWORD: {{ $password | b64enc | quote }}
  USERNAME: {{ .Values.service.authentication.username | b64enc | quote }}
{{- end }}
