services:
  otel-collector:
    image: otel/opentelemetry-collector:0.143.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  traefik:
    image: traefik:v3.6.5
    ports:
      - "80:80"
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --providers.docker.exposedbydefault=false
      - --tracing.serviceName="feature-traefik"
      - --tracing.otlp=true
      - --tracing.otlp.grpc=true
      - --tracing.otlp.grpc.insecure=true
      - --tracing.otlp.grpc.endpoint="otel-collector:4317"
      - --log.format=json
    depends_on:
      - ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  service:
    image: ghcr.io/dkrizic/feature:latest
    pull_policy: always
    ports:
      - name: http
        target: 8000
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - PORT=8000
      - PRESET=COLOR=red,THEME=dark,BOOKING=true
      - STORAGE_TYPE=inmemory
      - ENABLE_OPENTELEMETRY=true
      - OTLP_ENDPOINT=otel-collector:4317
  ui:
    image: ghcr.io/dkrizic/feature-ui:latest
    pull_policy: always
    ports:
      - name: http
        target: 8000
    environment:
      - PORT=8000
      - ENDPOINT=service:8000
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - ENABLE_OPENTELEMETRY=true
      - OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ui.entrypoints=web"
      - "traefik.http.services.ui.loadbalancer.server.port=8000"
  cli:
    image: ghcr.io/dkrizic/feature-cli:latest
    pull_policy: always
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - ENDPOINT=service:8000
      - ENABLE_OPENTELEMETRY=true
      - OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - service
